arti/arti/urls.py
from django.contrib import admin
from django.urls import path, include
from book.views import BookList, BookDetailView, BookCreateView, BookUpdateView, BookDeleteView, BookUpdateStateView, request_verification, deny_verification, verify, cancel_verification, BookSearch, AllBooksBeingTranslated, AllBooksDeniedTranslation, AllBooksRequestingVF, AllBooksVerified, UserBooksBeingTranslated, UserBooksDeniedTranslation, UserBooksRequestingVF,UserBooksVerified
from paragraph.views import ParagraphList, ParagraphForPageCreateView, ParagraphForPageUpdateView, ParagraphDeleteView
from pages.views import PageList, PageDetailView, PageForBookCreateView, PageForBookUpdateView, PageDeleteView
from django.conf.urls.static import static
from django.conf import settings
from PDF.views import generate_pdf
from . import views as core_views
from accounts.views import make_admin, UserList
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', core_views.signup, name='signup'),
    path('', BookList.as_view(), name='book-list' ),
    path('paragraph/', ParagraphList.as_view(), name='paragraph-list'),
    path('page/', PageList.as_view(), name='page-list'),
    path('book/<pk>', BookDetailView.as_view(), name='book-detail'),
    path('page/<pk>', PageDetailView.as_view(), name='page-detail'),
    path('create-book/', BookCreateView.as_view(), name='book-create'),
    path('create-page/<book_id>/', PageForBookCreateView.as_view(), name='page-create'),
    path('create-paragraph/<page_id>/', ParagraphForPageCreateView.as_view(), name='paragraph-create'),
    path('update-paragraph/<pk>', ParagraphForPageUpdateView.as_view(), name='paragraph-update'),
    path('update-page/<pk>', PageForBookUpdateView.as_view(), name='page-update'),
    path('update-book/<pk>', BookUpdateView.as_view(), name='book-update'),
    path('delete-book/<pk>', BookDeleteView.as_view(), name='book-delete'),
    path('delete-page/<pk>', PageDeleteView.as_view(), name='page-delete'),
    path('delete-paragraph/<pk>', ParagraphDeleteView.as_view(), name='paragraph-delete'),
    path('generate-pdf/<book_id>', generate_pdf, name='generate-pdf'),
    path('make-admin/<user_id>', make_admin, name='make-admin'),
    path('user-list', UserList.as_view(), name='user-list'),
    path('edit-state/<pk>', BookUpdateStateView.as_view(), name='edit-state'),
    path('request-verification/<book_id>', request_verification, name='request-verification'),
    path('deny-verification/<book_id>', deny_verification, name='deny-verification'),
    path('verify/<book_id>', verify, name='verify'),
    path('cancel-verification/<book_id>', cancel_verification, name='cancel-verification'),
    path('book-search', BookSearch.as_view(), name='book-search'),
    path('book-being-translated', AllBooksBeingTranslated.as_view(), name='book-being-translated'),
    path('book-verified', AllBooksVerified.as_view(), name='book-verified'),
    path('book-denied-translation', AllBooksDeniedTranslation.as_view(), name='book-denied-translation'),
    path('book-request-verification', AllBooksRequestingVF.as_view(), name='book-request-verification'),
    path('book-request-verification', AllBooksRequestingVF.as_view(), name='book-request-verification'),
    path('user-book-verification', UserBooksRequestingVF.as_view(), name='user-book-verification'),
    path('user-book-translated', UserBooksBeingTranslated.as_view(), name='user-book-translated'),
    path('user-book-denied', UserBooksDeniedTranslation.as_view(), name='user-book-denied'),
    path('user-book-verified', UserBooksVerified.as_view(), name='user-book-verified'),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arti/pages/models.py
from django.db import models
from book.models import Book

class Page(models.Model):
    page_no = models.IntegerField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='pictures',max_length=255, null=True, blank=True)

arti/paragraph/models.py
from django.db import models
from pages.models import Page


class Paragraph(models.Model):
    text = models.TextField()
    font_size = models.IntegerField()
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    paragraph_no = models.IntegerField(default=1)
    CENTER = 'C'
    LEFT = 'L'
    RIGHT = 'R'
    justification_choices = [
        (CENTER, 'Center'),
        (LEFT, 'Left'),
        (RIGHT, 'Right'),
    ]
    justification = models.CharField(
        max_length=6,
        choices=justification_choices,
        default=CENTER,
    )

arti/templates/base.html
{% load static  %}

<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<script
			src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
				 integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
				 crossorigin="anonymous"></script>		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

		<title> {% block title %} {%endblock%} : Arti</title>


	</head>
	<body>
		<script src="{% static 'js/kantipur.js' %}"></script>
		<script src="{% static 'js/base.js' %}"></script>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<a class="navbar-brand" href="#">ARTI</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
					</li>
                    <li class="nav-item active">
						<a class="nav-link" href="/">Hello {{ user.username }} <span class="sr-only">(current)</span></a>
					</li>
{% if request.user.is_staff %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'user-list' %}">View Users</a>
    </li>
{% endif %}
    <li class="nav-item active">
    {% if user.is_authenticated %}
    <a type="button" href ="{% url 'logout' %}" class="btn btn-sm btn-secondary navbar-btn">Logout</a>
    {% else %}
    <a type="button" href ="{% url 'login' %}" class="btn btn-sm btn-secondary navbar-btn">Login</a>
    {% endif %}
    </li>

					{% block links %} {% endblock %}
					<div class="nav pull-right">
						<button type="button" class="btn btn-sm btn-secondary navbar-btn"  onclick="toggle_use_kantipur();" id="toggle-kantipur"></button>
					</div>

					<!--<li class="nav-item dropdown">
						 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						 Dropdown
						 </a>
						 <div class="dropdown-menu" aria-labelledby="navbarDropdown">
						 <a class="dropdown-item" href="#">Action</a>
						 <a class="dropdown-item" href="#">Another action</a>
						 <div class="dropdown-divider"></div>
						 <a class="dropdown-item" href="#">Something else here</a>
						 </div>
						 </li>-->
  </div>
</nav>
    <div class="container-fluid">
      {% block headers %} {% endblock %}
      
      {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  </body>
</html>

arti/templates/book_detail.html
{% extends "base.html" %}

{% block title %} Book Detail {% endblock  %}

{% block links %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'page-create' object.id %}">Add Page</a>
    </li>
{% endblock %}
{% block headers %}
    <h1 style="text-align:center;text-transform:uppercase">{{ object.title}}</h1>
    <a class="btn btn-warning" href="{% url 'book-update' book.id %}">Edit Book</a>
    
    {% if book.book_image %}
                    <a href="{% url 'book-detail' book.id %}"><img src="{{ book.book_image.url }}" class="rounded mx-auto d-block" height=200 width=200/></a>
                {% else %}
                    <img src="../media/pictures/imagenotfound.png" class="rounded mx-auto d-block" height=200 width=200/>
                {% endif %}
{% endblock %}

{% block content %}
    <a href="{% url 'generate-pdf' book.id %}">Generate PDF</a>
    {% if book.state == 'BT' %}
        <a href="{% url 'request-verification' book.id %}" class="btn btn-primary">Request Verification</a>
    {% elif book.state == 'VR' %}
        {% if request.user.is_staff %}
            <a href="{% url 'deny-verification' book.id %}" class="btn btn-primary">Deny Verification</a>
            <a href="{% url 'verify' book.id %}" class="btn btn-primary">Verify</a>
        {% endif %}
        <a href="{% url 'cancel-verification' book.id %}" class="btn btn-primary">Cancel Verification Request</a>
    {% elif book.state == 'VD' %}
        <a href="{% url 'request-verification' book.id %}" class="btn btn-primary">Request Verification</a>
    {% elif book.state == 'VF' %}
        <i class="fas fa-check-circle"></i>
    {% endif %}
        
    <h2>Pages for this book</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Page no.</th>
          <th scope="col">Book id</th>
          <th scope="col"> </th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
          {% for page in object.get_all_pages %}
            <tr>
              <td>{{ page.page_no }}</td>
              <td>{{ page.book.id }}</td>
              <td><a href="{% url 'page-detail' page.id %}">View Page</a></td>
              <td><a href="{% url 'page-update' page.id %}">Edit Page</a></td>
              <td><a href="{% url 'page-delete' page.id %}">Delete Page</a></td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
        
{% endblock %}
   
  

<!--<table>
  {% for page in object.page_set.all %}
  <tr>
    <td>{{ page.page_no }}</td>
    <td>{{ page.book.id }}</td>
    <td><a href="{% url 'page-detail' page.id %}">View Page</a></td>

    <td><a href="{% url 'page-update' page.id %}">Edit Page</a></td>
    <td><a href="{% url 'page-delete' page.id %}">Delete Page</a></td>
  </tr>
  {% endfor %}-->

arti/templates/book_list.html
{% extends "base.html" %}


{% block title %} Home {% endblock  %}

{% block links %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'book-create' %}">Create Book</a>
    </li>
    <li class="nav-item dropdown">
						 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						 All books
						 </a>
						 <div class="dropdown-menu" aria-labelledby="navbarDropdown">
						 <a class="dropdown-item" href="{% url 'book-being-translated' %}">Being Translated</a>
						 <a class="dropdown-item" href="{% url 'book-request-verification' %}">Requesting Verification</a>
                         <a class="dropdown-item" href="{% url 'book-verified' %}">Verified</a>
						 <a class="dropdown-item" href="{% url 'book-denied-translation' %}">Verification Denied</a>
						 </div>
						 </li>
    <li class="nav-item dropdown">
						 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						 My books
						 </a>
						 <div class="dropdown-menu" aria-labelledby="navbarDropdown">
						 <a class="dropdown-item" href="{% url 'user-book-translated' %}">Being Translated</a>
						 <a class="dropdown-item" href="{% url 'user-book-verification' %}">Requesting Verification</a>
                         <a class="dropdown-item" href="{% url 'user-book-verified' %}">Verified</a>
						 <a class="dropdown-item" href="{% url 'user-book-denied' %}">Verification Denied</a>
						 </div>
						 </li>
    
{% endblock %}
{% block content %}

<form class="form-inline" method=GET action="{% url 'book-search' %}">
      <div class="mx-auto">  
  
    <label for="title" class="sr-only">Title</label>
    <input type="text" id="title" name="title" placeholder="Title of Book">
  
  <button type="submit" class="btn btn-primary mb-2" style="margin-top:6px">Search</button>
  </div>
</form>
    <div class="row">
        {% for book in object_list %}
            <div class="col-4 mb-3 mt-3">
                
                
                <div class="card bg-light mb-3" style="max-width: 18rem;">
                {% if book.book_image %}
                    <a href="{% url 'book-detail' book.id %}"><img src="{{ book.book_image.url }}" class="card-img-top", height=200/></a>
                {% else %}
                    <img src="../media/pictures/imagenotfound.png" class="card-img-top", height=200/>
                {% endif %}
                <div class="card-header" style="text-transform:uppercase;font-family:American Typewriter,serif"><a href="{% url 'book-detail' book.id %}">{{ book.id}}. {{ book.title}}</a></div>
                <div class="card-header" style="text-transform:uppercase;font-family:American Typewriter,serif">
                    <p>Author: {{ book.author }}</p>
                    <p>Price: {{ book.price }}</p>
                    <p>State: {{book.get_state_name }}</p>
                
                
                </div>
                <div class="card-body">
                
                    <a class="btn btn-warning" href="{% url 'book-update' book.id %}" class="card-link">Edit Book</a>
                    <a class="btn btn-danger" href="{% url 'book-delete' book.id %}" class="card-link">Delete Book</a>
                    
                </div>
                </div>
            </div>      
            
        {% endfor %}
    </div>
    </div>


<!--<table class="table">
{% for book in object_list %}
  <tr>
    <td><a href="{% url 'book-detail' book.id %}">{{ book.id}}. {{ book.title}}</a></td>
    <td><a href="{% url 'book-update' book.id %}">Edit Book</a></td>
    <td><a href="{% url 'book-delete' book.id %}">Delete Book</a></td>
  </tr>
{% endfor %}
</table>-->
{% endblock%}

arti/templates/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col col-6">
    <form class="form" method="post" enctype="multipart/form-data">

<script>
 function changeFontSize() {
	 font_size = $("#id_font_size").val();
	 $("#id_text").attr("style", `font-size:${font_size}px`)
 }


 $(document).ready(function() {
	 changeFontSize();
	 $("#id_font_size").on("change keydown keypress keyup mousedown click mouseup", changeFontSize)
 });

</script>

<div class="col col-8">
    <form class="form" method="post">

    {% csrf_token %}
        {{form | crispy }}
    <input class="btn btn-primary" type="submit" value="Save">
</form>

</div>


{% endblock %}

arti/templates/delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm">
</form>
{% endblock %}

arti/templates/error.html
{% extends 'base.html' %}

{% block content %}
<p> You cannot perform this action</p>
<a href="javascript: history.go(-1)">Go Back</a>

{% endblock %}

arti/templates/page_detail.html
{% extends "base.html" %}

{% block title %}Page Detail{% endblock %}

{% block links %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'book-detail' page.book.id %}">View Book</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'paragraph-create' page.id %}">Create Paragraph</a>
        
    </li>
  
{% endblock %}
{% block headers %}
    <h3 style="text-align:center">Page no: {{ page.page_no }}</h3>
    <div class="container">
        <div class="row">
            <div class="col">
                          {% if page.image %}
       <img src="{{ page.image.url }}" class="image" height=200/>
                {% else %}
                    <img src="/media/pictures/imagenotfound.png" class="rounded mx-auto d-block", height=200/>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %} 

{% block content %}    
    {% for paragraph in page.paragraph_set.all %}
        <div class ="row">
        <div class="col-12">
     <div class="card">
  <div class="card-body">

    <h5 class="card-title"><h1>{{ forloop.counter0|add:paragraph.paragraph_no }}</h1></h5>
    <p style="font-size:{{paragraph.font_size}}px" class="card-text">{{ paragraph.text }}</p>
    
    <a class="btn btn-warning" href="{% url 'paragraph-update' paragraph.id %}" class="card-link">Edit Paragraph</a>
    <a class="btn btn-danger" href="{% url 'paragraph-delete' paragraph.id %}" class="card-link">Delete Paragraph</a>
  </div>
</div>
</div>
</div>
{% endfor %}

    
{% endblock %} 
    
   <!-- <table>
      {% for paragraph in page.paragraph_set.all %}
        <tr>
          <td>{{ paragraph.id }}</td>
          <td>{{ paragraph.text }}</td>
          <td>{{ paragraph.font_size }}</td>
          <td><a href="{% url 'paragraph-update' paragraph.id %}">Edit Paragraph</a></td>
          <td><a href="{% url 'paragraph-delete' paragraph.id %}">Delete Paragraph</a></td>
        </tr>
      {% endfor %}
    </table>-->

arti/templates/page_list.html
<table>
{% for page in object_list %}
  <tr>
    <td>{{ page.page_no }}</td>
    <td>{{ page.book.id }}</td>
    <td><a href="{% url 'page-update' page.id %}">Edit Page</a></td>
    <td><a href="{% url 'page-delete' page.id %}">Delete Page</a></td>
  </tr>
{% endfor %}
</table>

arti/templates/paragraph_list.html
{% for paragraph in object_list %}
  <p>{{ paragraph.text }}</p>
  <p>{{ paragraph.font_size }}</p>
  <p>{{ paragraph.page.page_no }}</p>
{% endfor %}

arti/templates/user_list.html
{% extends "base.html" %}
{% block content %}
{% if request.user.is_staff %}
    <table class="table">
        <thead class="thead-dark">
        <tr>
          <th scope="col">User ID</th>
          <th scope="col">Uername</th>
          <th scope="col"></th>
          <th scope="col"></th>

          
        </tr>
      </thead>
      <tbody>
          {% for user in object_list %}
        <tr>
          <th scope="row">{{ user.user_id }}</th>
          <td>{{ user.username }}</td>
          <td>{{ user.is_staff}}</td>
          <td><a class="btn btn-primary" href="{% url 'make-admin' user.id %}" class="card-link">Make Admin</a></td>
          
        </tr>
        {% endfor %}
{% endif %}
        
{% endblock %}